In [1]:
# library package
import pandas as pd

In [2]:
df = pd.read_excel('data.xlsx')
df.Discount = df.Discount.astype(int)
df.Discounted_Price = df.Discounted_Price.astype(int)

In [3]:
print('\nHere is the list of 30 items to select with $1000 budget and max discount: \n')
print(df)

Here is the list of 30 items to select with $1000 budget and max discount:

                   Item  Discounted_Price  Original_Price  Discount
0           Formal shoe                23           36.99        13
1                Tablet                29           49.99        20
2             Headphone                59          149.99        90
3               Printer                19           59.99        40
4               Speaker                44           59.99        15
5               Sneaker                55           89.95        34
6          Running Shoe                66           85.00        19
7                 Watch                74           91.75        16
8      Wireless speaker                99          199.00       100
9                Jogger                40           54.00        13
10          Arsenal kit                83           90.00         6
11             Gym shoe                56           69.95        13
12           Laptop bag                97          113.97        15
13  Bluetooth headphone                78          129.99        51
14           Skateboard                36           59.99        22
15              Sweater                25           27.82         2
16        PS controller                38           64.99        25
17           GTA V game                84           99.99        15
18          Bike helmet                29           33.96         3
19          Hair dryer                 38           59.99        20
20            Bed sheet                31           39.78         7
21                Shirt                27           39.99        12
22           Power bank                39           46.99         7
23             Sunglass                34           89.99        55
24             Swimsuit                31           54.00        22
25        Aquarium tank                27           32.89         5
26               Blazer                85           99.99        14
27        Kitchen mixer                37           39.67         2
28       Microwave bowl                15           17.99         1
29       Protein powder                23           28.99         5

In [4]:
discount = list(df['Discount'])
price = list(df['Discounted_Price'])
capital = 1000

col = capital + 1
row = len(discount)
dp = [[0 for _ in range(col)] for _ in range(row)]

In [5]:
for item in range(row):
    for budget in range(col):
        if price[item] > budget:
            dp[item][budget] = dp[item-1][budget]
            continue
        previous_best_discount = dp[item-1][budget]
        new_best_discount = discount[item] + dp[item-1][budget - price[item]]
        dp[item][budget] = max(previous_best_discount, new_best_discount)
solutions = []
for row in dp:
    for col in row:
        solutions.append(col)
max_discount = max(solutions)
knapsack_table = pd.DataFrame(dp)     

choosen_items = []
j = capital
for i in range (len(discount)-1,0,-1):
    if dp[i][j] != dp[i-1][j]:
        choosen_items.insert(0,i)
        j -= price[i]
total_items = len(choosen_items)

df_final = df.iloc[choosen_items]

pricelist = list (df_final['Discounted_Price'])
total_price = 0
for object in pricelist:
    total_price += object

In [6]:
print ('\nFrom knapsack-DP algorithm, maximum discount is: $',max_discount)
print ('\nFollowing is the Knapsack table formed using DP:\n')
print (knapsack_table)
print ('\nTotal number of items to buy for max discount is:',total_items)
print ('\nAnd we need to buy items with following indices:',choosen_items)
print ('\nTotal money used from budget of $1000 in purchase is: $',total_price)

print('\n')
print('Following is the table of purchase decision:\n')
print(df_final)

From knapsack-DP algorithm, maximum discount is: $ 609

Following is the Knapsack table formed using DP:

    0     1     2     3     4     5     6     7     8     9     ...  991   \
0      0     0     0     0     0     0     0     0     0     0  ...    13
1      0     0     0     0     0     0     0     0     0     0  ...    33
2      0     0     0     0     0     0     0     0     0     0  ...   123
3      0     0     0     0     0     0     0     0     0     0  ...   163
4      0     0     0     0     0     0     0     0     0     0  ...   178
5      0     0     0     0     0     0     0     0     0     0  ...   212
6      0     0     0     0     0     0     0     0     0     0  ...   231
7      0     0     0     0     0     0     0     0     0     0  ...   247
8      0     0     0     0     0     0     0     0     0     0  ...   347
9      0     0     0     0     0     0     0     0     0     0  ...   360
10     0     0     0     0     0     0     0     0     0     0  ...   366
11     0     0     0     0     0     0     0     0     0     0  ...   379
12     0     0     0     0     0     0     0     0     0     0  ...   394
13     0     0     0     0     0     0     0     0     0     0  ...   445
14     0     0     0     0     0     0     0     0     0     0  ...   467
15     0     0     0     0     0     0     0     0     0     0  ...   469
16     0     0     0     0     0     0     0     0     0     0  ...   494
17     0     0     0     0     0     0     0     0     0     0  ...   507
18     0     0     0     0     0     0     0     0     0     0  ...   507
19     0     0     0     0     0     0     0     0     0     0  ...   526
20     0     0     0     0     0     0     0     0     0     0  ...   530
21     0     0     0     0     0     0     0     0     0     0  ...   536
22     0     0     0     0     0     0     0     0     0     0  ...   537
23     0     0     0     0     0     0     0     0     0     0  ...   587
24     0     0     0     0     0     0     0     0     0     0  ...   605
25     0     0     0     0     0     0     0     0     0     0  ...   607
26     0     0     0     0     0     0     0     0     0     0  ...   607
27     0     0     0     0     0     0     0     0     0     0  ...   607
28     0     0     0     0     0     0     0     0     0     0  ...   607
29     0     0     0     0     0     0     0     0     0     0  ...   607

    992   993   994   995   996   997   998   999   1000
0     13    13    13    13    13    13    13    13    13
1     33    33    33    33    33    33    33    33    33
2    123   123   123   123   123   123   123   123   123
3    163   163   163   163   163   163   163   163   163
4    178   178   178   178   178   178   178   178   178
5    212   212   212   212   212   212   212   212   212
6    231   231   231   231   231   231   231   231   231
7    247   247   247   247   247   247   247   247   247
8    347   347   347   347   347   347   347   347   347
9    360   360   360   360   360   360   360   360   360
10   366   366   366   366   366   366   366   366   366
11   379   379   379   379   379   379   379   379   379
12   394   394   394   394   394   394   394   394   394
13   445   445   445   445   445   445   445   445   445
14   467   467   467   467   467   467   467   467   467
15   469   469   469   469   469   469   469   469   469
16   494   494   494   494   494   494   494   494   494
17   507   507   507   507   507   507   507   507   507
18   507   507   507   507   507   507   507   507   507
19   526   526   526   526   526   526   526   526   526
20   530   530   530   531   531   531   531   531   531
21   536   540   540   540   540   540   540   540   540
22   537   540   540   540   540   540   540   540   540
23   587   587   589   589   589   589   590   590   590
24   605   605   605   605   605   605   605   605   609
25   607   607   607   607   607   607   607   607   609
26   607   607   607   607   607   607   607   607   609
27   607   607   607   607   607   607   607   607   609
28   607   607   607   607   607   607   607   607   609
29   607   607   607   607   607   607   607   608   609

[30 rows x 1001 columns]

Total number of items to buy for max discount is: 20

And we need to buy items with following indices: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 14, 16, 17, 19, 20, 21, 22, 23, 24]

Total money used from budget of $1000 in purchase is: $ 977


Following is the table of purchase decision:

                   Item  Discounted_Price  Original_Price  Discount
1                Tablet                29           49.99        20
2             Headphone                59          149.99        90
3               Printer                19           59.99        40
4               Speaker                44           59.99        15
5               Sneaker                55           89.95        34
6          Running Shoe                66           85.00        19
7                 Watch                74           91.75        16
8      Wireless speaker                99          199.00       100
9                Jogger                40           54.00        13
11             Gym shoe                56           69.95        13
13  Bluetooth headphone                78          129.99        51
14           Skateboard                36           59.99        22
16        PS controller                38           64.99        25
17           GTA V game                84           99.99        15
19          Hair dryer                 38           59.99        20
20            Bed sheet                31           39.78         7
21                Shirt                27           39.99        12
22           Power bank                39           46.99         7
23             Sunglass                34           89.99        55
24             Swimsuit                31           54.00        22